DEFAULT_ACTION_LABELS = [
    "standing",
    "sitting",
    "kneeling",
    "crouching",
    "lying",
    "falling",
    "walking",
    "running",
    "arms raised",
    "restrained",
    "aiming",
    "attacking",
    "defending",
    "carrying",
    "injured depiction",
    "motionless depiction",
    "captured",
    "celebrating",
    "surrendering",
]
