REVIEW_ACTIONS = [
    "accept",
    "reject",
    "edit",
    "add_detection",
    "remove_detection",
    "change_class",
    "change_group",
    "merge_tracks",
    "split_track",
    "correct_ocr",
    "correct_transcript",
    "correct_relation",
    "correct_codebook",
    "mark_ambiguous",
]
